//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Core.BestServerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarErbsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPService() {
            this.Url = global::Core.Properties.Settings.Default.Core_BestServerService_SOAPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarErbsCompletedEventHandler ConsultarErbsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarErbs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BestServer[] ConsultarErbs(double x, double y) {
            object[] results = this.Invoke("ConsultarErbs", new object[] {
                        x,
                        y});
            return ((BestServer[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarErbsAsync(double x, double y) {
            this.ConsultarErbsAsync(x, y, null);
        }
        
        /// <remarks/>
        public void ConsultarErbsAsync(double x, double y, object userState) {
            if ((this.ConsultarErbsOperationCompleted == null)) {
                this.ConsultarErbsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarErbsOperationCompleted);
            }
            this.InvokeAsync("ConsultarErbs", new object[] {
                        x,
                        y}, this.ConsultarErbsOperationCompleted, userState);
        }
        
        private void OnConsultarErbsOperationCompleted(object arg) {
            if ((this.ConsultarErbsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarErbsCompleted(this, new ConsultarErbsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BestServer {
        
        private int ordemField;
        
        private string ufField;
        
        private string tecnologiaField;
        
        private string siglaErbField;
        
        private int setorField;
        
        private int frequenciaField;
        
        private string cGIField;
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        public int Ordem {
            get {
                return this.ordemField;
            }
            set {
                this.ordemField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Tecnologia {
            get {
                return this.tecnologiaField;
            }
            set {
                this.tecnologiaField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaErb {
            get {
                return this.siglaErbField;
            }
            set {
                this.siglaErbField = value;
            }
        }
        
        /// <remarks/>
        public int Setor {
            get {
                return this.setorField;
            }
            set {
                this.setorField = value;
            }
        }
        
        /// <remarks/>
        public int Frequencia {
            get {
                return this.frequenciaField;
            }
            set {
                this.frequenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CGI {
            get {
                return this.cGIField;
            }
            set {
                this.cGIField = value;
            }
        }
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultarErbsCompletedEventHandler(object sender, ConsultarErbsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarErbsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarErbsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BestServer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BestServer[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591