//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Core.GeocodeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarMunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeocodeReversoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEnderecoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPService() {
            this.Url = global::Core.Properties.Settings.Default.Core_GeocodeService_SOAPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarMunicipiosCompletedEventHandler BuscarMunicipiosCompleted;
        
        /// <remarks/>
        public event GeocodeReversoCompletedEventHandler GeocodeReversoCompleted;
        
        /// <remarks/>
        public event BuscarEnderecoCompletedEventHandler BuscarEnderecoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarMunicipios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Municipio[] BuscarMunicipios(string pUF) {
            object[] results = this.Invoke("BuscarMunicipios", new object[] {
                        pUF});
            return ((Municipio[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarMunicipiosAsync(string pUF) {
            this.BuscarMunicipiosAsync(pUF, null);
        }
        
        /// <remarks/>
        public void BuscarMunicipiosAsync(string pUF, object userState) {
            if ((this.BuscarMunicipiosOperationCompleted == null)) {
                this.BuscarMunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarMunicipiosOperationCompleted);
            }
            this.InvokeAsync("BuscarMunicipios", new object[] {
                        pUF}, this.BuscarMunicipiosOperationCompleted, userState);
        }
        
        private void OnBuscarMunicipiosOperationCompleted(object arg) {
            if ((this.BuscarMunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarMunicipiosCompleted(this, new BuscarMunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeocodeReverso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IGeocode[] GeocodeReverso(double pX, double pY, string pDistancia, string pSisCoord) {
            object[] results = this.Invoke("GeocodeReverso", new object[] {
                        pX,
                        pY,
                        pDistancia,
                        pSisCoord});
            return ((IGeocode[])(results[0]));
        }
        
        /// <remarks/>
        public void GeocodeReversoAsync(double pX, double pY, string pDistancia, string pSisCoord) {
            this.GeocodeReversoAsync(pX, pY, pDistancia, pSisCoord, null);
        }
        
        /// <remarks/>
        public void GeocodeReversoAsync(double pX, double pY, string pDistancia, string pSisCoord, object userState) {
            if ((this.GeocodeReversoOperationCompleted == null)) {
                this.GeocodeReversoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeocodeReversoOperationCompleted);
            }
            this.InvokeAsync("GeocodeReverso", new object[] {
                        pX,
                        pY,
                        pDistancia,
                        pSisCoord}, this.GeocodeReversoOperationCompleted, userState);
        }
        
        private void OnGeocodeReversoOperationCompleted(object arg) {
            if ((this.GeocodeReversoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeocodeReversoCompleted(this, new GeocodeReversoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEndereco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IGeocode[] BuscarEndereco(string pUF, string pMunicipio, string pEndereco, string pCep, string pPonto, string pSisCoord, string pCandidatos, string pPrioridade) {
            object[] results = this.Invoke("BuscarEndereco", new object[] {
                        pUF,
                        pMunicipio,
                        pEndereco,
                        pCep,
                        pPonto,
                        pSisCoord,
                        pCandidatos,
                        pPrioridade});
            return ((IGeocode[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEnderecoAsync(string pUF, string pMunicipio, string pEndereco, string pCep, string pPonto, string pSisCoord, string pCandidatos, string pPrioridade) {
            this.BuscarEnderecoAsync(pUF, pMunicipio, pEndereco, pCep, pPonto, pSisCoord, pCandidatos, pPrioridade, null);
        }
        
        /// <remarks/>
        public void BuscarEnderecoAsync(string pUF, string pMunicipio, string pEndereco, string pCep, string pPonto, string pSisCoord, string pCandidatos, string pPrioridade, object userState) {
            if ((this.BuscarEnderecoOperationCompleted == null)) {
                this.BuscarEnderecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEnderecoOperationCompleted);
            }
            this.InvokeAsync("BuscarEndereco", new object[] {
                        pUF,
                        pMunicipio,
                        pEndereco,
                        pCep,
                        pPonto,
                        pSisCoord,
                        pCandidatos,
                        pPrioridade}, this.BuscarEnderecoOperationCompleted, userState);
        }
        
        private void OnBuscarEnderecoOperationCompleted(object arg) {
            if ((this.BuscarEnderecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEnderecoCompleted(this, new BuscarEnderecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Municipio {
        
        private string iBGEField;
        
        private string iBGE_NField;
        
        private string nomePadraoField;
        
        private string nomeField;
        
        private string uF_EntradaField;
        
        /// <remarks/>
        public string IBGE {
            get {
                return this.iBGEField;
            }
            set {
                this.iBGEField = value;
            }
        }
        
        /// <remarks/>
        public string IBGE_N {
            get {
                return this.iBGE_NField;
            }
            set {
                this.iBGE_NField = value;
            }
        }
        
        /// <remarks/>
        public string NomePadrao {
            get {
                return this.nomePadraoField;
            }
            set {
                this.nomePadraoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string UF_Entrada {
            get {
                return this.uF_EntradaField;
            }
            set {
                this.uF_EntradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MapaCertoEndereco))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcGisOnlineEndereco))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VivoEndereco))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class IGeocode {
        
        private string objectIDField;
        
        private string uF_EntradaField;
        
        private string municipio_EntradaField;
        
        private string endereco_EntradaField;
        
        private string bairro_EntradaField;
        
        private string cep_EntradaField;
        
        private string ponto_EntradaField;
        
        private string candidatos_EntradaField;
        
        private string prioridade_EntradaField;
        
        private string sisCoord_EntradaField;
        
        private string zona_EntradaField;
        
        private string outPutField;
        
        private string latitude_EntradaField;
        
        private string longitude_EntradaField;
        
        private string distanciaBuffer_EntradaField;
        
        private string pOIField;
        
        private string eND_POIField;
        
        private string ufField;
        
        private string iBGE_NField;
        
        private string iBGEField;
        
        private string municipioField;
        
        private string bairroField;
        
        private string cEPField;
        
        private string tipoField;
        
        private string tituloField;
        
        private string logradouroField;
        
        private int numIniField;
        
        private int numFimField;
        
        private System.Nullable<double> quilometroField;
        
        private double xField;
        
        private double yField;
        
        private int prioridadeField;
        
        private string sis_CoordField;
        
        private string zonaField;
        
        private double scoreField;
        
        private double centroField;
        
        private string distanciaField;
        
        private string enderecoEncontradoField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string UF_Entrada {
            get {
                return this.uF_EntradaField;
            }
            set {
                this.uF_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Municipio_Entrada {
            get {
                return this.municipio_EntradaField;
            }
            set {
                this.municipio_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Entrada {
            get {
                return this.endereco_EntradaField;
            }
            set {
                this.endereco_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro_Entrada {
            get {
                return this.bairro_EntradaField;
            }
            set {
                this.bairro_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Cep_Entrada {
            get {
                return this.cep_EntradaField;
            }
            set {
                this.cep_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Ponto_Entrada {
            get {
                return this.ponto_EntradaField;
            }
            set {
                this.ponto_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Candidatos_Entrada {
            get {
                return this.candidatos_EntradaField;
            }
            set {
                this.candidatos_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Prioridade_Entrada {
            get {
                return this.prioridade_EntradaField;
            }
            set {
                this.prioridade_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string SisCoord_Entrada {
            get {
                return this.sisCoord_EntradaField;
            }
            set {
                this.sisCoord_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Zona_Entrada {
            get {
                return this.zona_EntradaField;
            }
            set {
                this.zona_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string OutPut {
            get {
                return this.outPutField;
            }
            set {
                this.outPutField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude_Entrada {
            get {
                return this.latitude_EntradaField;
            }
            set {
                this.latitude_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude_Entrada {
            get {
                return this.longitude_EntradaField;
            }
            set {
                this.longitude_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string DistanciaBuffer_Entrada {
            get {
                return this.distanciaBuffer_EntradaField;
            }
            set {
                this.distanciaBuffer_EntradaField = value;
            }
        }
        
        /// <remarks/>
        public string POI {
            get {
                return this.pOIField;
            }
            set {
                this.pOIField = value;
            }
        }
        
        /// <remarks/>
        public string END_POI {
            get {
                return this.eND_POIField;
            }
            set {
                this.eND_POIField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string IBGE_N {
            get {
                return this.iBGE_NField;
            }
            set {
                this.iBGE_NField = value;
            }
        }
        
        /// <remarks/>
        public string IBGE {
            get {
                return this.iBGEField;
            }
            set {
                this.iBGEField = value;
            }
        }
        
        /// <remarks/>
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public int NumIni {
            get {
                return this.numIniField;
            }
            set {
                this.numIniField = value;
            }
        }
        
        /// <remarks/>
        public int NumFim {
            get {
                return this.numFimField;
            }
            set {
                this.numFimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Quilometro {
            get {
                return this.quilometroField;
            }
            set {
                this.quilometroField = value;
            }
        }
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public int Prioridade {
            get {
                return this.prioridadeField;
            }
            set {
                this.prioridadeField = value;
            }
        }
        
        /// <remarks/>
        public string Sis_Coord {
            get {
                return this.sis_CoordField;
            }
            set {
                this.sis_CoordField = value;
            }
        }
        
        /// <remarks/>
        public string Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <remarks/>
        public double Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public double Centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
            }
        }
        
        /// <remarks/>
        public string Distancia {
            get {
                return this.distanciaField;
            }
            set {
                this.distanciaField = value;
            }
        }
        
        /// <remarks/>
        public string EnderecoEncontrado {
            get {
                return this.enderecoEncontradoField;
            }
            set {
                this.enderecoEncontradoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MapaCertoEndereco : IGeocode {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArcGisOnlineEndereco : IGeocode {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VivoEndereco : IGeocode {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarMunicipiosCompletedEventHandler(object sender, BuscarMunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarMunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarMunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Municipio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Municipio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GeocodeReversoCompletedEventHandler(object sender, GeocodeReversoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeocodeReversoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeocodeReversoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IGeocode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IGeocode[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarEnderecoCompletedEventHandler(object sender, BuscarEnderecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEnderecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEnderecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IGeocode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IGeocode[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591